name: Albus
main: net.districtmine.ant59.albus
version: 2.0
commands:
  albus:
    description: Albus commands
    usage: |
      /<command> reload - reloads the whitelist and settings
      /<command> list - list whitelist entries